-- AlterTable
ALTER TABLE `ContactMessage` ADD COLUMN `email` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `message` VARCHAR(191) NOT NULL;
